version: "3.9"

services:
  wazuh.manager:
    image: wazuh/wazuh-manager:latest
    hostname: wazuh.manager
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "55000:55000"
    volumes:
      - wazuh_data:/var/ossec/data

  wazuh.indexer:
    image: wazuh/wazuh-indexer:latest
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    volumes:
      - wazuh_indexer:/usr/share/wazuh-indexer/data

  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:latest
    ports:
      - "5601:5601"
    depends_on:
      - wazuh.indexer

volumes:
  wazuh_data:
  wazuh_indexer:
